wandb_version: 1

CWS_params:
  desc: null
  value:
    ratio: 2
    rot: true
    sigma_factor: 6
_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.12
    start_time: 1641490776
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 1
      - 2
      - 16
      4: 3.7.12
      5: 0.12.9
      8:
      - 1
      - 5
batch_size:
  desc: null
  value: 8
decoder_channels:
  desc: null
  value:
  - 64
  - 64
  - 64
  - 32
  - 32
encoder_channels:
  desc: null
  value:
  - 32
  - 32
  - 64
  - 64
  - 64
kernlen:
  desc: null
  value: 31
learning_rate:
  desc: null
  value: 0.0001
loss_scale:
  desc: null
  value: 1000
nsig:
  desc: null
  value: 4
num_epochs:
  desc: null
  value: 300
rel_threshold:
  desc: null
  value: 0.002
resize:
  desc: null
  value: 0.25
segmentation_model_fp:
  desc: null
  value: segmentation_models/SDD_segmentation.pth
semantic_classes:
  desc: null
  value: 6
temperature:
  desc: null
  value: 1.8
unfreeze:
  desc: null
  value: 100
use_CWS:
  desc: null
  value: true
use_TTST:
  desc: null
  value: true
use_features_only:
  desc: null
  value: false
viz_epoch:
  desc: null
  value: 10
waypoints:
  desc: null
  value:
  - 14
  - 29
